### PR TITLE
Add optional show_progress

### PR DESCRIPTION
**Pull request by tavinathanson**
Often, `tqdm` prints progress bars on multiple lines and it can be annoying to scroll through. @jburos any idea why?

Until we resolve that, perhaps we can just make `tqdm` optional? Hence this PR.

### CODE REVIEW

**Comment by jburos** [comment]
@tavinathanson agreed - i've noticed that too. When I was testing previously, this happened when logger tried to write to stdout or other status things used `print` instead of logger for example. Any of these things that write to stdout directly break compatibility with tqdm. It might makes sense to create an issue for this - #207 

Re: implementation, we could probably leave this even if `tqdm` printing is fixed, since this would also allow us to remove the strict dependency on `tqdm`. What do you think about removing this from `requirements.txt` & defaulting `show_progress` to False if `tqdm` is not installed?

I noticed this was done for `rpy2` in [PyVCF](https://github.com/jamescasbon/PyVCF/blob/master/vcf/filters.py#L1): 

```py
try:
    from rpy2 import robjects
except:
    robjects = None
```

**Comment by tavinathanson** [comment]
@jburos cool, thanks for filing that issue. I suppose the downside of not requiring `tqdm` would be that people wouldn't automatically install it on a `pip install cohorts` and may not know that they're missing it.

Not sure who we're focused on helping with not requiring `tqdm` at the moment? Maybe worth tabling, and avoiding the slight increase in complexity, until/unless anyone has issues with that?

**Comment by jburos** [comment]
@tavinathanson was just thinking the fewer requirements the better, overall. OK if you want to table. in PyVCF, the user sees a message if they try to use a feature that requires rpy2 but it isn't installed, so that they know to install it. But admittedly, rpy2 is messier than tqdm.

**Comment by jburos** [comment]
Otherwise, LGTM. OK to merge!

**Comment by tavinathanson** [comment]
@jburos I generally agree with the fewer requirements the better, though it feels a little unnecessary at this point given our low number of requirements.

Happy to keep the conversation going, but will merge for now.

**Pull request merged**
