### PR TITLE
Allow extra keyword arguments in functions

### PR DESCRIPTION
**Pull request by tavinathanson**
Allows arbitrary arguments in functions. Example:

```
def snv_count(row, hello, **kwargs):
    return hello

cohort.as_dataframe(snv_count, hello="new message")
```

@arahuja

### CODE REVIEW

**Comment by arahuja** [comment]
@tavinathanson what happens if I have multiple functions?

**Comment by tavinathanson** [comment]
@arahuja like this?

```
def snv_count(row, fn_1, fn_2, **kwargs):
    fn_1(2)
    fn_2(3)
    return 1

cohort.as_dataframe(snv_count, fn_1=lambda x: 2, fn_2=lambda x: 3)
```

That works, unless I'm misunderstanding the question?

**Comment by arahuja** [comment]
@tavinathanson sorry I meant
`cohort.as_dataframe([snv_count, missense_snv_count])`

**Comment by tavinathanson** [comment]
@arahuja looks like it applies them to both, e.g.:

```
def snv_count(row, fn_1, fn_2, **kwargs):
    fn_1(2)
    fn_2(3)
    return 1

def snv_count_2(row, fn_1, fn_2, **kwargs):
    fn_1(2)
    fn_2(3)
    return 1

cohort.as_dataframe([snv_count, snv_count_2], fn_1=lambda x: 2, fn_2=lambda x: 3)
```

And ends up in an error if they don't take the same parameters.

If you need to use two functions with different parameters, you can wrap the functions in lambdas vs. passing them via `as_dataframe` arguments.

Does that seem reasonable/expected?

**Comment by tavinathanson** [comment]
Spoke with @arahuja offline; he suggested that passing kwargs to multiple functions is weird/unexpected.

@arahuja as of the last commit, this works:

```
cohort.as_dataframe({"snv_count": lambda row: snv_count(row, fn_1=lambda x: 2),
                     "snv_count_2": lambda row: snv_count_2(row, fn_1=lambda x: 3)})
```

This errors:

```
cohort.as_dataframe([snv_count, snv_count_2], fn_1=lambda x: 2, fn_2=lambda x: 3)
```

**Comment by tavinathanson** [comment]
@arahuja good to merge?

**Comment by arahuja** [comment]
@tavinathanson Did this always a allow a dict? Did not know that. The amount of options (list or func or dict) still seems weird, but if that is how it has been before, looks good.

**Comment by tavinathanson** [comment]
It did, and the code is largely reused between `dict` and `list`. It's there to make it easier to specify the column names. Here, with just a list of `lambda`s, the columns would just default to `column_0` and `column_1`. Does that make sense?

**Pull request merged**
