### PR TITLE
Pass stat_func through jointplot

### PR DESCRIPTION
**Pull request by tavinathanson**
Used this to look at `spearmanr`.

Separately, passed some `kwargs` through in `cohort_bootstrap_auc` so things like `filter_fn` could be passed through.

@arahuja

### CODE REVIEW

**Comment by tavinathanson** [comment]
@arahuja @e5c just added a `CorrelationResults` returned by `plot_joint`, and made the statistical test and plot configurable. (I needed to show a boxplot, for example.)

**Comment by tavinathanson** [comment]
Current example usage:

```
cohort.plot_joint({"PD-L1": lambda row: int(row["PD-L1"].split("IC")[1]),
                                    "T-cell fraction": 
                                      lambda row: row["T-cell fraction"]},
                                    plot_type="boxplot",
                                    stat_func=spearmanr)
```

**Comment by tavinathanson** [comment]
@e5c just added a quick change so that `x` vs. `y` are better specified. https://github.com/hammerlab/cohorts/pull/125/commits/97be610dd20b478d6596eaa0c24c701463df48b5

**Comment by tavinathanson** [comment]
@e5c added `jointplot_kwargs` so that we can say e.g.:

```
cohort.plot_joint({"PD-L1 IC": lambda row: int(row["PD-L1"].split("IC")[1]),
                                   "TIL Fraction": 
                                     lambda row: row["T-cell fraction"]},
                                   plot_type="jointplot",
                                   jointplot_kwargs={"kind": "reg"},
                                   x_col="PD-L1 IC",
                                   stat_func=spearmanr)
```

**Comment by e5c** [comment]
LGTM

**Pull request merged**
